title: Hello, world! I'm Sam Edelstein
description: > # this means to ignore newlines until "baseurl:"
  Sam Edelstein's personal website.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sam Edelstein # add your name
author-img: SamEdelstein.jpg # add your photo
about-author: Chief Data Officer for the City of Syracuse. # add description
social-twitter: samedelstein
social-facebook: # add your Facebook handle
social-github: samedelstein # add your Github handle
social-linkedin: samedelstein
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
